### ISSUE TITLE
teleport portals

### ISSUE THREAD

**Issue by Tunarslan** [nytelytee/geode-wave-trail-drag-fix#5] opened 2024-03-23 05:54 UTC
the wave trail doesn't cut of when i enter a teleport portal

Uploading GeometryDash 2024-03-23 08-54-11-075.mp4…

**Comment by nytelytee** [comment] 2024-03-23 06:03
This was fixed in v1.1.1, but there seems to have been a regression.

**Comment by nytelytee** [comment] 2024-03-23 06:15
wtf, I can only reproduce this on fps <= 163

**Comment by nytelytee** [comment] 2024-03-23 06:34
Alright I figured it out, still not sure why it only happens on some fps, but yeah it seems to be a regression in v1.1.6.

**Comment by nytelytee** [comment] 2024-03-23 06:37
Try the latest action build when it finishes. If it works, I will make a new release.

**Closed** 2024-04-10 15:16 UTC
